server:
  port: 8000

spring:
  application:
    name: xdclass-video-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud_user?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  zipkin:
    base-url: http://192.168.224.128:9411/
    discovery-client-enabled: false #不开启服务发现
  sleuth:
    sampler:
      probability: 1.0 #采样百分比
# 控制台输出sql、下划线转驼峰
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true